/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.Color;
import javax.swing.border.AbstractBorder;
import models.*;
/**
 *
 * @author Carlos
 */
public class MensajeView extends javax.swing.JPanel {

    public String id;
    public String mensaje;
    
    public Index index;
    public MensajeView() {
        initComponents();
        // AbstractBorder brdr = new TextBubbleBorder(Color.BLACK,2,16,0);
        //setBorder(brdr);
        this.setOpaque(false);
        this.setBackground(new Color(255,255,255,0));
    }

    public void setMensaje(String mensaje) {
        this.mensaje = mensaje;
        this.text.setText(mensaje);
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public void setSizeText(int x,int y){
        this.text.setSize(x, y);
    }
    public void SetTrash(){
        this.trash.setVisible(false);
        revalidate();
        repaint();
    }

    public void setIndex(Index index) {
        this.index = index;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        text = new javax.swing.JEditorPane();
        trash = new javax.swing.JLabel();

        text.setEditable(false);
        text.setBackground(new java.awt.Color(152, 184, 203));
        text.setBorder(null);
        text.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N

        trash.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/if_icon-26-trash-can_315224.png"))); // NOI18N
        trash.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        trash.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                trashMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(text, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(trash, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(trash, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 59, Short.MAX_VALUE))
            .addComponent(text)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void trashMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_trashMouseClicked
       
        index.socket.WriteText("REMOVEMSG "+this.id);
        this.text.setText("Este mensaje fue eliminado");
        this.text.setForeground(Color.red);
        this.mensaje="";
        SetTrash();
        
    }//GEN-LAST:event_trashMouseClicked
    
    public void eliminarMsg(){
        this.mensaje="";
        this.text.setText("Este mensaje fue eliminado");
        this.text.setForeground(Color.red);
       
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane text;
    private javax.swing.JLabel trash;
    // End of variables declaration//GEN-END:variables
}
